### ISSUE TITLE
GUI is ugly on Linux

### ISSUE THREAD

**Issue by etxmato** [etxmato/emma_02#2]

**Comment by etxmato** [comment]
Finally closing this one, I think it is now 'acceptable', due to HD crash I made a new Ubuntu installation where it all looks rather 'ok'. I have hopefully tested / checked all of them.

**Comment by phiber1** [comment]
Hmmmm... I just did a pull 10 minutes ago, and a clean build. Removed all
ini files that were left behind and did a "first-time" run...
Unfortunately, the "Clock" field and "Start" button are cut off by the
bottom of the window. I can resize it larger, but the change doesn't stick.
I have to resize every time.
Very strange, because this *was* working. Now it isn't.  :(

**Comment by etxmato** [comment]
Fixed this one just now, i.e. now after you re-size Emma 02 will open in the same size as when you exited. Default window size will be reset on 'default all' in settings menu.

**Comment by phiber1** [comment]
I've verified that it once again saves the window size between runs.  :)
However, on initial run, it's still too small; this may still confuse
people, especially since it's the "Start" button that's cut off and people
wouldn't be able to start any machines unless they first resized. Not so
good...
